#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# This wizard provisions SSH key MATERIAL only — it never calls the GitHub
# API and never registers anything. Registration happens later, manually,
# via this repo's own post-attach.sh prompt once the devcontainer is open.
# Scope, reuse rules, and permissions below come from a wayfinder decision
# ("SSH key wizard scope") — see .scratch/devcontainer-host-walkthrough/.

# Remembers CREDENTIAL_DIR/DEPLOY_KEY_LABEL across re-runs without touching
# any project .env — this wizard's state is its own, host-side concern.
ENV_FILE="$HOME/.devcontainer-credentials/.provision-ssh-keys.env"
SHARED_SIGNING_DIR="$HOME/.devcontainer-credentials"

TOTAL_STAGES=3

banner "Devcontainer SSH keys"

# ── Stage 1: locate the Credential Directory for this repo ────────────────
stage "Credential Directory"
say "This repo's devcontainer reads SSH credentials from a host directory"
say "named by DEVCONTAINER_CREDENTIALS_DIR — never from inside the repo."
if [[ -z "${CREDENTIAL_DIR:-}" ]]; then
  ask CREDENTIAL_DIR "Credential Directory for this repo (absolute path):"
fi
if [[ -z "${DEPLOY_KEY_LABEL:-}" ]]; then
  ask DEPLOY_KEY_LABEL "Label for the deploy key (e.g. owner/repo):"
fi
mkdir -p "$CREDENTIAL_DIR" "$SHARED_SIGNING_DIR"
chmod 700 "$CREDENTIAL_DIR" "$SHARED_SIGNING_DIR"
write_env CREDENTIAL_DIR "$CREDENTIAL_DIR"
write_env DEPLOY_KEY_LABEL "$DEPLOY_KEY_LABEL"

# _keygen_into PATH COMMENT: generates a fresh ED25519 pair at PATH(.pub),
# refusing to clobber an existing one without explicit confirmation.
_keygen_into() {
  local path="$1" comment="$2"
  if [[ -f "$path" ]]; then
    warn "$path already exists."
    confirm "Overwrite it with a freshly generated key?" || { note "kept the existing key"; return 0; }
    rm -f "$path" "$path.pub"
  fi
  ssh-keygen -t ed25519 -N "" -C "$comment" -f "$path" >/dev/null
  chmod 600 "$path"
  chmod 644 "$path.pub"
  printf '  %s✓ generated%s %s\n' "$GREEN" "$RESET" "$path"
}

# _copy_into SRC DEST: copies SRC(.pub) to DEST(.pub), refusing to clobber an
# existing, different DEST without explicit confirmation.
_copy_into() {
  local src="$1" dest="$2"
  if [[ -f "$dest" ]] && ! cmp -s "$src" "$dest"; then
    warn "$dest already exists and differs from $src."
    confirm "Overwrite it?" || { note "kept the existing key at $dest"; return 0; }
  fi
  cp "$src" "$dest"
  cp "$src.pub" "$dest.pub"
  chmod 600 "$dest"
  chmod 644 "$dest.pub"
}

# ── Stage 2: deploy key — always fresh, this repo is the only place it's used
stage "Deploy key (repo-scoped)"
say "GitHub allows registering a deploy key on only one repository, so this"
say "one is always generated fresh for $DEPLOY_KEY_LABEL — never reused."
_keygen_into "$CREDENTIAL_DIR/deploy-key" "$DEPLOY_KEY_LABEL deploy key"

# ── Stage 3: signing key — account-scoped, reused across every repo ───────
stage "Signing key (account-scoped, shared across repos)"
say "Unlike the deploy key, your signing key isn't tied to one repository —"
say "it's your identity for every signed commit, so it's worth reusing."
SHARED_SIGNING_KEY="$SHARED_SIGNING_DIR/signing-key"
if [[ -f "$SHARED_SIGNING_KEY" ]]; then
  note "found an existing shared signing key: $SHARED_SIGNING_KEY"
  if confirm "Reuse it for this repo too?"; then
    _copy_into "$SHARED_SIGNING_KEY" "$CREDENTIAL_DIR/signing-key"
    printf '  %s✓ reused%s %s\n' "$GREEN" "$RESET" "$SHARED_SIGNING_KEY"
  else
    _keygen_into "$CREDENTIAL_DIR/signing-key" "$(whoami)@$(hostname -s 2>/dev/null || hostname) signing key"
  fi
else
  note "no shared signing key yet — generating one, kept at $SHARED_SIGNING_DIR for reuse."
  _keygen_into "$SHARED_SIGNING_KEY" "$(whoami)@$(hostname -s 2>/dev/null || hostname) signing key"
  _copy_into "$SHARED_SIGNING_KEY" "$CREDENTIAL_DIR/signing-key"
fi

finish

printf '\n%s%sPaste these into GitHub once the container is open%s\n' "$BOLD" "$BLUE" "$RESET"
note "(post-attach.sh prompts for this automatically on first attach — this"
note "wizard only got the key material in place, it registered nothing)"
printf '\n  %sDeploy key%s (register as an Authentication Key, this repo only):\n' "$BOLD" "$RESET"
cat "$CREDENTIAL_DIR/deploy-key.pub"
printf '\n  %sSigning key%s (register as a Signing Key, once per account):\n' "$BOLD" "$RESET"
cat "$CREDENTIAL_DIR/signing-key.pub"
printf '\n'
