#!/bin/bash
set -euo pipefail

# Reads the Base Version Marker (see CONTEXT.md) in the current repo's
# .devcontainer/ and reports whether it satisfies a CLI Skill's declared
# metadata.requires-setup-devcontainer caret range. Base-owned: CLI Skills
# call it from step 1, the same way they call patch-if-absent.sh.

usage() {
  cat >&2 <<'EOF'
Usage: check-base-version.sh <caret-range> [<devcontainer-dir>]

<caret-range>:      an npm caret range such as ^1.0.0.
<devcontainer-dir>: defaults to .devcontainer.

Exit codes:
  0  the Base Version Marker is within the range
  1  the marker is outside the range: re-run setup-devcontainer first
  2  usage error (including a range that is not a caret range)
  3  no Base Version Marker: the container predates versioning
  4  the marker is malformed
EOF
}

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
  usage
  exit 2
fi

RANGE="$1"
DIR="${2:-.devcontainer}"
MARKER="$DIR/.setup-devcontainer-version"
SEMVER='^([0-9]+)\.([0-9]+)\.([0-9]+)$'

if ! [[ "$RANGE" =~ ^\^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
  echo "check-base-version.sh: '$RANGE' is not a caret range such as ^1.0.0" >&2
  usage
  exit 2
fi
floor_major="${BASH_REMATCH[1]}" floor_minor="${BASH_REMATCH[2]}" floor_patch="${BASH_REMATCH[3]}"

if [ ! -f "$MARKER" ]; then
  echo "no Base Version Marker at $MARKER: this container predates setup-devcontainer versioning. Re-run setup-devcontainer to record one."
  exit 3
fi

version="$(tr -d '[:space:]' < "$MARKER")"
if ! [[ "$version" =~ $SEMVER ]]; then
  echo "the Base Version Marker at $MARKER is malformed ('$version'). Re-run setup-devcontainer to rewrite it."
  exit 4
fi
major="${BASH_REMATCH[1]}" minor="${BASH_REMATCH[2]}" patch="${BASH_REMATCH[3]}"

# npm caret semantics: the leftmost non-zero component of the floor is fixed.
in_range=false
if [ "$major" -eq "$floor_major" ]; then
  if [ "$floor_major" -gt 0 ]; then
    if [ "$minor" -gt "$floor_minor" ] || { [ "$minor" -eq "$floor_minor" ] && [ "$patch" -ge "$floor_patch" ]; }; then in_range=true; fi
  elif [ "$floor_minor" -gt 0 ]; then
    if [ "$minor" -eq "$floor_minor" ] && [ "$patch" -ge "$floor_patch" ]; then in_range=true; fi
  elif [ "$minor" -eq 0 ] && [ "$patch" -eq "$floor_patch" ]; then
    in_range=true
  fi
fi

if [ "$in_range" = true ]; then
  echo "setup-devcontainer $version satisfies $RANGE"
  exit 0
fi

echo "this container was generated by setup-devcontainer $version, outside $RANGE. Re-run setup-devcontainer first, then this skill."
exit 1
